name: worldsocialintegrationapp
description: "Wow's"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  agora_rtc_engine: ^6.3.2
  audio_waveforms: ^1.0.5
  audioplayers: ^6.1.0
  buttons_tabbar: ^1.3.13
  cached_network_image: ^3.3.1
  chewie: ^1.8.3
  country_code_picker: ^3.0.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.1
  dio: ^5.5.0+1
  dropdown_button2: ^2.3.9
  emoji_picker_flutter: ^2.2.0
  file_picker: null
  files_scanner_android: ^1.0.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_database: ^11.1.0
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.3.0
  flutter_chat_bubble: ^2.0.2
  flutter_confetti: ^0.3.0
  flutter_facebook_auth: ^7.0.1
  flutter_localization: ^0.2.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  inview_notifier_list: ^3.0.0
  jwt_decode: ^0.3.1
  kbspinningwheel: ^1.0.3
  otp_pin_field: ^1.2.9+1
  path: ^1.9.0
  permission_handler: ^11.3.1
  polar_tab_bar: ^0.0.2
  provider: ^6.1.2
  social_login_buttons: ^1.0.7
  svgaplayer_flutter_rhr: ^2.2.1
  timeago: ^3.7.0
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/
    - assets/svg/country/
    - assets/dummy/

flutter_native_splash:
  image: assets/image/wow_logo_512.png
  color: "#ffffff"
  web_image_mode: center
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/image/android_splash.png
    image_dark: assets/image/android_splash.png

# flutter pub run flutter_native_splash:create
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/wow_logo.png"
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
    image_path: "assets/image/wow_logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
# flutter pub run flutter_launcher_icons:main
