name: worldsocialintegrationapp
description: "Wow's"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  country_code_picker: ^3.0.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  emoji_picker_flutter: ^2.2.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.3.0
  flutter_facebook_auth: ^7.0.1
  flutter_localization: ^0.2.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  otp_pin_field: ^1.2.9+1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  social_login_buttons: ^1.0.7
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/
    - assets/dummy/

flutter_native_splash:
  image: assets/image/wow_logo_192.png
  color: "#ffffff"
  web_image_mode: center
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/image/android_splash.png
    image_dark: assets/image/android_splash.png

# flutter pub run flutter_native_splash:create
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/wow_logo.png"
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
    image_path: "assets/image/wow_logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
# flutter pub run flutter_launcher_icons:main
