List<String> bankList = [
  'Andhra Pradesh Grameena Vikas Bank',
  'Axis Bank',
  'Bank of Baroda',
  'Bank of India',
  'Bank of Maharashtra',
  'Barclays Bank',
  'Baroda UP Bank',
  'Bassein Catholic Co-operative Bank',
  'Canara Bank',
  'Central Bank of India',
  'Citibank',
  'Deutsche Bank',
  'Federal Bank',
  'HDFC Bank',
  'HSBC',
  'ICICI Bank',
  'IDBI Bank',
  'IDFC First Bank',
  'Indian Bank',
  'IndusInd Bank',
  'Janata Sahakari Bank',
  'Kerala Gramin Bank',
  'Kotak Mahindra Bank',
  'Punjab National Bank',
  'Punjab & Sind Bank',
  'Prathama UP Gramin Bank',
  'RBL Bank',
  'Sarva UP Gramin Bank',
  'Saraswat Co-operative Bank',
  'Shamrao Vithal Co-operative Bank',
  'South Indian Bank',
  'Standard Chartered Bank',
  'State Bank of India',
  'TJSB Sahakari Bank',
  'Union Bank of India',
  'UCO Bank',
  'Yes Bank'
];
