import '../models/user_profile_detail.dart';
import '../models/visitor_model.dart';

class UserProfileDetailConverter {
  static VisitorModel toVisitorModel(UserProfileDetail? userProfileDetail) {
    return VisitorModel(
      id: userProfileDetail?.id ?? '',
      name: userProfileDetail?.name ?? '',
      username: userProfileDetail?.username ?? '',
      familyId: userProfileDetail?.familyId ?? '',
      phone: userProfileDetail?.phone ?? '',
      facebookUserName: userProfileDetail?.facebookUserName ?? '',
      email: userProfileDetail?.email ?? '',
      hostStatus: userProfileDetail?.hostStatus ?? '',
      socialId: userProfileDetail?.socialId ?? '',
      fbSocialId: userProfileDetail?.fbSocialId ?? '',
      snapSocialId: userProfileDetail?.snapSocialId ?? '',
      myExp: userProfileDetail?.myExp ?? '',
      myRecieveExperience: userProfileDetail?.myRecieveExperience ?? '',
      vipLevel: userProfileDetail?.vipLevel ?? '',
      vipFrom: userProfileDetail?.vipFrom ?? '',
      vipTo: userProfileDetail?.vipTo ?? '',
      myLevel: userProfileDetail?.myLevel ?? '',
      receivingLevel: userProfileDetail?.receivingLevel ?? '',
      myCoin: userProfileDetail?.myCoin ?? '',
      myDiamond: userProfileDetail?.myDiamond ?? '',
      totalSendDiamond: userProfileDetail?.totalSendDiamond ?? '',
      myRecievedDiamond: userProfileDetail?.myRecievedDiamond ?? '',
      dob: userProfileDetail?.dob ?? '',
      bio: userProfileDetail?.bio ?? '',
      country: userProfileDetail?.country ?? '',
      continent: userProfileDetail?.continent ?? '',
      countryShowUnshow: userProfileDetail?.countryShowUnshow ?? '',
      myFrame: userProfileDetail?.myFrame ?? '',
      myGallery: userProfileDetail?.myGallery ?? '',
      myLuckyId: userProfileDetail?.myLuckyId ?? '',
      myTheme: userProfileDetail?.myTheme ?? '',
      myThemeType: userProfileDetail?.myThemeType ?? '',
      emailVerifiedAt: userProfileDetail?.emailVerifiedAt ?? '',
      password: userProfileDetail?.password ?? '',
      salt: userProfileDetail?.salt ?? '',
      isAdmin: userProfileDetail?.isAdmin ?? '',
      image: userProfileDetail?.image ?? '',
      langId: userProfileDetail?.langId ?? '',
      age: userProfileDetail?.age ?? '',
      gender: userProfileDetail?.gender ?? '',
      devId: userProfileDetail?.devId ?? '',
      regId: userProfileDetail?.regId ?? '',
      latitude: userProfileDetail?.latitude ?? '',
      longitude: userProfileDetail?.longitude ?? '',
      devType: userProfileDetail?.devType ?? '',
      rememberToken: userProfileDetail?.rememberToken ?? '',
      loginOtp: userProfileDetail?.loginOtp ?? '',
      loginType: userProfileDetail?.loginType ?? '',
      registerType: userProfileDetail?.registerType ?? '',
      createdAt: userProfileDetail?.createdAt ?? '',
      updatedAt: userProfileDetail?.updatedAt ?? '',
      phoneUpOtp: userProfileDetail?.phoneUpOtp ?? '',
      eventId: userProfileDetail?.eventId ?? '',
      isEventCreater: userProfileDetail?.isEventCreater ?? '',
      isEventSubscriber: userProfileDetail?.isEventSubscriber ?? '',
      isFamilyLeader: userProfileDetail?.isFamilyLeader ?? '',
      isFamilyMember: userProfileDetail?.isFamilyMember ?? '',
      monthlyCoins: userProfileDetail?.monthlyCoins ?? '',
      hoursLive: userProfileDetail?.hoursLive ?? '',
      talentLevel: userProfileDetail?.talentLevel ?? '',
      basicSalary: userProfileDetail?.basicSalary ?? '',
      userBanStatus: userProfileDetail?.userBanStatus ?? '',
      idBannedFrom: userProfileDetail?.idBannedFrom ?? '',
      idBannedTo: userProfileDetail?.idBannedTo ?? '',
      liveimage: userProfileDetail?.liveimage ?? '',
      imageText: userProfileDetail?.imageText ?? '',
      imageTitle: userProfileDetail?.imageTitle ?? '',
      fixedValidDay: userProfileDetail?.fixedValidDay ?? '',
      fixedMinutes: userProfileDetail?.fixedMinutes ?? '',
      fixedCoins: userProfileDetail?.fixedCoins ?? '',
      imageDp: userProfileDetail?.profileImage ?? '',
      sandColor: userProfileDetail?.country ?? '',
      sandBgImage: userProfileDetail?.continent ?? '',
      sendLevel: userProfileDetail?.myLevel ?? '',
      sendExp: userProfileDetail?.myExp ?? '',
      sendStart: userProfileDetail?.lavelInfomation?.sendStart ?? 0,
      sendEnd: userProfileDetail?.lavelInfomation?.sendEnd ?? 0,
      reciveColor: userProfileDetail?.receivingLevel ?? '',
      reciveBgImage: userProfileDetail?.countryShowUnshow ?? '',
      reciveLevel: userProfileDetail?.receivingLevel ?? '',
      reciveExp: userProfileDetail?.myRecieveExperience ?? '',
      reciveStart: userProfileDetail?.lavelInfomation?.reciveStart ?? 0,
      reciveEnd: userProfileDetail?.lavelInfomation?.reciveEnd ?? 0,
    );
  }
}
